### PR TITLE
Updates countdown.js for count-up functionality

### PR DESCRIPTION
**Pull request by ErikAugust**
One line change to add count up functionality.

### CODE REVIEW

**Comment by hilios** [comment]
Hey man, thanks for the PR, I am still worried with backwards functionality and need a way to allow the toggle of the functionality somehow.

But first, please fix the code style guideline that is failing: https://travis-ci.org/hilios/jQuery.countdown/builds/53245928

**Comment by ErikAugust** [comment]
No worries, that makes sense - what's the easiest way to make that formatting fix?

**Comment by hilios** [comment]
Just keep the line bellow 80 columns, your text-editor should help set a ruler!

**Comment by ErikAugust** [comment]
Ha - I hear ya. I'll push a fixed up version.



On Wed, Mar 11, 2015 at 10:45 AM, Edson Hilios <notifications@github.com>
wrote:

> Just keep the line bellow 80 columns, your text-editor should help set a
> ruler!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hilios/jQuery.countdown/pull/104#issuecomment-78303258>
> .
>



-- 

Erik August Johnson
erikaugust.com
(802) 343-4640

**Pull request closed without merging**
